version: 3
images:
  base_image:
    name: ghcr.io/ansible-community/community-ee-base:latest
dependencies:
  ansible_core:
    package_pip: ansible-core==2.20.0
  ansible_runner:
    package_pip: ansible-runner
  python:
    - podman
    - requests
  system:
    - podman
    - buildah
    - skopeo
    - git
    - tar
  galaxy: requirements.yml